openapi: 3.0.0
info:
  title: Consortia Configuration integration API
  description: "Consortia Configuration integration API"
  version: 0.0.1
paths:
  /consortia-configuration:
    get:
      summary: Get consortium configuration
      operationId: getConfiguration
      responses:
        '200':
          $ref: '#/components/responses/ConsortiaConfiguration'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Save consortia configuration
      operationId: saveConfiguration
      responses:
        '201':
          $ref: '#/components/responses/ConsortiaConfiguration'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      requestBody:
        $ref: '#/components/requestBodies/ConfigurationBody'
    delete:
      summary: Delete consortia configuration
      operationId: deleteConfiguration
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  requestBodies:
    ConfigurationBody:
      description: Consortia configuration object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/consortiaConfiguration.yaml#/ConsortiaConfiguration"
  responses:
    ConsortiaConfiguration:
      description: Consortia configuration object
      content:
        application/json:
          schema:
            $ref: "schemas/consortiaConfiguration.yaml#/ConsortiaConfiguration"
    NoContent:
      description: No content
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
