openapi: 3.0.0
info:
  title: Consortium integration API
  description: "Consortium integration API"
  version: 0.0.1
paths:
  /consortia:
    get:
      summary: Get consortium collection
      operationId: getConsortiumCollection
      responses:
        '200':
          $ref: '#/components/responses/ConsortiumCollection'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Save consortium
      operationId: saveConsortium
      responses:
        '201':
          $ref: '#/components/responses/Consortium'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
      requestBody:
        $ref: '#/components/requestBodies/ConsortiumBody'
  /consortia/{consortiumId}:
    get:
      summary: Get consortium record based on consortiumId
      operationId: getConsortium
      parameters:
        - $ref: '#/components/parameters/consortiumId'
      responses:
        '200':
          $ref: '#/components/responses/Consortium'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update consortium name
      operationId: updateConsortium
      parameters:
        - $ref: '#/components/parameters/consortiumId'
      responses:
        '200':
          $ref: '#/components/responses/Consortium'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      requestBody:
        $ref: '#/components/requestBodies/ConsortiumBody'
components:
  requestBodies:
    ConsortiumBody:
      description: Consortium object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/consortium.yaml#/Consortium"
  responses:
    Consortium:
      description: Consortium Object
      content:
        application/json:
          schema:
            $ref: "schemas/consortium.yaml#/Consortium"
    ConsortiumCollection:
      description: Collection of Consortium Object
      content:
        application/json:
          schema:
            $ref: "schemas/consortium.yaml#/ConsortiumCollection"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    Conflict:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: 'schemas/common.yaml#/Errors'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    consortiumId:
      in: path
      name: consortiumId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of consortium

  schemas:
    userCollection:
      $ref: 'schemas/user.yaml#/UserCollection'
    userCapabilitySetsRequest:
      $ref: schemas/capability/user/userCapabilitySetsRequest.json
    capability-sets:
      $ref: schemas/capability/capabilitySets.json
