openapi: 3.0.0
info:
  title: Sharing policy integration API
  description: "Sharing policy integration API"
  version: 0.0.1
servers:
  - url: /consortia/{consortiumId}/sharing
paths:
  /policies:
    post:
      summary: start sharing policy
      operationId: startSharingPolicy
      parameters:
        - $ref: "#/components/parameters/consortiumId"
      requestBody:
        $ref: "#/components/requestBodies/SharingPolicyBody"
      responses:
        "201":
          $ref: "#/components/responses/SharingPolicyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /policies/{policyId}:
    delete:
      summary: delete sharing policy
      operationId: deleteSharingPolicy
      parameters:
        - $ref: "#/components/parameters/consortiumId"
        - $ref: "#/components/parameters/policyId"
      requestBody:
        $ref: "#/components/requestBodies/SharingPolicyBody"
      responses:
        "200":
          $ref: "#/components/responses/SharingPolicyDeleteResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  requestBodies:
    SharingPolicyBody:
      description: Sharing policies object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/sharingPolicy.yaml#/SharingPolicyRequest"
          example:
            $ref: "examples/requests/sharing_policy_request_for_roles.json"
  responses:
    SharingPolicyResponse:
      description: Returns a sharing policy object response for post operation
      content:
        application/json:
          schema:
            $ref: "schemas/sharingPolicy.yaml#/SharingPolicyResponse"
          example:
            $ref: "examples/responses/sharing_policy_response.json"
    SharingPolicyDeleteResponse:
      description: Returns a sharing policy response for delete operation
      content:
        application/json:
          schema:
            $ref: "schemas/sharingPolicy.yaml#/SharingPolicyDeleteResponse"
          example:
            $ref: "examples/responses/sharing_policy_delete_response.json"
    NoContent:
      description: No content
    Conflict:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: 'schemas/common.yaml#/Errors'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    consortiumId:
      in: path
      name: consortiumId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of consortium
    policyId:
      in: path
      name: policyId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of policy
