openapi: 3.0.0
info:
  title: Sharing instance and setting integration API
  description: "Sharing instance and setting integration API"
  version: 0.0.1
servers:
  - url: /consortia/{consortiumId}/sharing
paths:
  /instances:
    get:
      description: Sharing instances
      summary: Get list of sharing instances
      operationId: getSharingInstances
      parameters:
        - $ref: "#/components/parameters/consortiumId"
        - $ref: "#/components/parameters/instanceIdentifier"
        - $ref: "#/components/parameters/sourceTenantId"
        - $ref: "#/components/parameters/targetTenantId"
        - $ref: "#/components/parameters/status"
        - $ref: "#/components/parameters/trait_pageable_offset"
        - $ref: "#/components/parameters/trait_pageable_limit"
      responses:
        "200":
          $ref: "#/components/responses/SharingInstanceCollection"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      summary: start instance sharing
      operationId: startSharingInstance
      parameters:
        - $ref: "#/components/parameters/consortiumId"
      requestBody:
        $ref: "#/components/requestBodies/SharingInstanceBody"
      responses:
        "201":
          $ref: "#/components/responses/SharingInstance"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /instances/{actionId}:
    get:
      summary: Get Sharing instance by action ID
      operationId: getSharingInstanceById
      parameters:
        - $ref: "#/components/parameters/consortiumId"
        - $ref: "#/components/parameters/actionId"
      responses:
        "200":
          $ref: "#/components/responses/SharingInstance"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  requestBodies:
    SharingInstanceBody:
      description: Sharing Instance object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/sharingInstance.yaml#/SharingInstance"
  responses:
    SharingInstance:
      description: Returns a sharing instance object object
      content:
        application/json:
          schema:
            $ref: "schemas/sharingInstance.yaml#/SharingInstance"
    SharingInstanceCollection:
      description: Returns list of sharing instances
      content:
        application/json:
          schema:
            $ref: "schemas/sharingInstance.yaml#/SharingInstanceCollection"
    NoContent:
      description: No content
    Conflict:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: 'schemas/common.yaml#/Errors'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    consortiumId:
      in: path
      name: consortiumId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of consortium
    actionId:
      in: path
      name: actionId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of sharing instance
    instanceIdentifier:
      in: query
      name: instanceIdentifier
      schema:
        $ref: "schemas/common.yaml#/uuid"
      description: The UUID of the instance
    sourceTenantId:
      in: query
      name: sourceTenantId
      schema:
        type: string
      description: The ID of the source tenant
    targetTenantId:
      in: query
      name: targetTenantId
      schema:
        type: string
      description: The ID of the target tenant
    status:
      in: query
      name: status
      schema:
        $ref: "schemas/status.yaml#/Status"
      description: The status of the sharing instance
    trait_pageable_offset:
      name: offset
      in: query
      description: Skip over a number of elements by specifying an offset value for
        the query
      schema:
        default: 0
        minimum: 0
        maximum: 2147483647
        type: integer
    trait_pageable_limit:
      name: limit
      in: query
      description: Limit the number of elements returned in the response
      schema:
        default: 10
        minimum: 0
        maximum: 2147483647
        type: integer
