openapi: 3.0.0
info:
  title: Sharing role integration API
  description: "Sharing role integration API"
  version: 0.0.1
servers:
  - url: /consortia/{consortiumId}/sharing
paths:
  /roles:
    post:
      summary: start sharing role
      operationId: startSharingRole
      tags:
        - roles
      parameters:
        - $ref: "#/components/parameters/consortiumId"
      requestBody:
        $ref: "#/components/requestBodies/SharingRoleBody"
      responses:
        "201":
          $ref: "#/components/responses/SharingRoleResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /roles/{roleId}:
    delete:
      summary: delete sharing role
      operationId: deleteSharingRole
      tags:
        - roles
      parameters:
        - $ref: "#/components/parameters/consortiumId"
        - $ref: "#/components/parameters/roleId"
      requestBody:
        $ref: "#/components/requestBodies/SharingRoleBody"
      responses:
        "200":
          $ref: "#/components/responses/SharingRoleDeleteResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /roles/capability-sets:
    post:
      summary: start sharing role capability sets
      operationId: startSharingRoleCapabilitySets
      tags:
        - role-capability-set
      parameters:
        - $ref: "#/components/parameters/consortiumId"
      requestBody:
        $ref: "#/components/requestBodies/SharingRoleCapabilitySetBody"
      responses:
        "201":
          $ref: "#/components/responses/SharingRoleCapabilitySetResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /roles/{roleId}/capability-sets:
    delete:
      summary: delete sharing role capability set
      operationId: deleteSharingRoleCapabilitySets
      tags:
        - role-capability-set
      parameters:
        - $ref: "#/components/parameters/consortiumId"
        - $ref: "#/components/parameters/roleId"
      requestBody:
        $ref: "#/components/requestBodies/SharingRoleCapabilitySetBody"
      responses:
        "200":
          $ref: "#/components/responses/SharingRoleCapabilitySetDeleteResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  requestBodies:
    SharingRoleBody:
      description: Sharing roles object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/sharingRole.yaml#/SharingRoleRequest"
    SharingRoleCapabilitySetBody:
      description: Sharing role capability sets object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/sharingRoleCapabilitySet.yaml#/SharingRoleCapabilitySetRequest"
  responses:
    SharingRoleResponse:
      description: Returns a sharing role object response for post operation
      content:
        application/json:
          schema:
            $ref: "schemas/sharingRole.yaml#/SharingRoleResponse"
    SharingRoleCapabilitySetResponse:
      description: Returns a sharing role capability set object response for post operation
      content:
        application/json:
          schema:
            $ref: "schemas/sharingRoleCapabilitySet.yaml#/SharingRoleCapabilitySetResponse"
    SharingRoleDeleteResponse:
      description: Returns a sharing role response for delete operation
      content:
        application/json:
          schema:
            $ref: "schemas/sharingRole.yaml#/SharingRoleDeleteResponse"
    SharingRoleCapabilitySetDeleteResponse:
      description: Returns a sharing role capability set response for delete operation
      content:
        application/json:
          schema:
            $ref: "schemas/sharingRoleCapabilitySet.yaml#/SharingRoleCapabilitySetDeleteResponse"
    NoContent:
      description: No content
    Conflict:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: 'schemas/common.yaml#/Errors'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    consortiumId:
      in: path
      name: consortiumId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of consortium
    roleId:
      in: path
      name: roleId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of role
