package org.folio.consortia.messaging.domain;

public enum ConsortiaOutputEventType {
  CONSORTIUM_PRIMARY_AFFILIATION_CREATED,
  CONSORTIUM_PRIMARY_AFFILIATION_UPDATED,
  CONSORTIUM_PRIMARY_AFFILIATION_DELETED,
  CONSORTIUM_INSTANCE_SHARING_INIT
}
