@startuml
title sd book room

actor Guest
participant Catalog
participant System
participant Booking
participant Room
participant Payment

activate Guest
Guest -> Catalog : searchRoom(price, style)
activate Catalog
Catalog --> Guest : return roomList
deactivate Catalog

Guest -> System : selectRoom()
activate System

alt roomStatus = available
    System --> Guest : ready to book
    Guest -> System : createBooking(room)
    System -> Booking : create
    activate Booking
    Booking -> Room : getBookingPrice()
    activate Room
    Room --> Booking : return bookingPrice
    deactivate Room
    Booking --> Guest : ready for payment
    deactivate Booking
    Guest -> Payment : initiatePayment(bookingPrice)
    activate Payment
    Payment -> Payment : process payment

    alt payment successful
        Payment --> Guest : payment succeeded
        Payment -> System : payment fulfilled
        deactivate Payment
        System -> Room : setRoomStatus(reserved)
        activate Room
        Room --> System : roomStatus updated
        deactivate Room
    else payment unsuccessful
        Payment --> Guest : payment failed
        deactivate Payment
    end

else roomStatus = unavailable
    System --> Guest : room unavailable
end

deactivate System
deactivate Guest

@enduml
